ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS job_page_logo_url text,
  ADD COLUMN IF NOT EXISTS job_page_logo_height integer NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS job_page_logo_radius integer NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS job_page_logo_padding integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS job_page_logo_bg_color text,
  ADD COLUMN IF NOT EXISTS job_page_logo_shadow boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS job_page_logo_border boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS job_page_brand_text_ar text DEFAULT 'ALKHOLI GROUP',
  ADD COLUMN IF NOT EXISTS job_page_brand_text_en text DEFAULT 'ALKHOLI GROUP',
  ADD COLUMN IF NOT EXISTS job_page_show_brand_text boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS job_page_description_title_ar text DEFAULT 'الوصف الوظيفي',
  ADD COLUMN IF NOT EXISTS job_page_description_title_en text DEFAULT 'Job Description',
  ADD COLUMN IF NOT EXISTS job_page_requirements_title_ar text DEFAULT 'المتطلبات',
  ADD COLUMN IF NOT EXISTS job_page_requirements_title_en text DEFAULT 'Requirements',
  ADD COLUMN IF NOT EXISTS job_page_additional_title_ar text DEFAULT 'تفاصيل إضافية',
  ADD COLUMN IF NOT EXISTS job_page_additional_title_en text DEFAULT 'Additional Details',
  ADD COLUMN IF NOT EXISTS job_page_apply_title_ar text DEFAULT 'مهتم بهذه الوظيفة؟',
  ADD COLUMN IF NOT EXISTS job_page_apply_title_en text DEFAULT 'Interested in this job?',
  ADD COLUMN IF NOT EXISTS job_page_apply_desc_ar text DEFAULT 'قدّم طلبك الآن وانضم لفريق مجموعة الخولي',
  ADD COLUMN IF NOT EXISTS job_page_apply_desc_en text DEFAULT 'Apply now and join the AlKholi Group team',
  ADD COLUMN IF NOT EXISTS job_page_apply_btn_ar text DEFAULT 'قدم الآن',
  ADD COLUMN IF NOT EXISTS job_page_apply_btn_en text DEFAULT 'Apply Now',
  ADD COLUMN IF NOT EXISTS job_page_card_bg text,
  ADD COLUMN IF NOT EXISTS job_page_card_border_color text,
  ADD COLUMN IF NOT EXISTS job_page_card_radius integer NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS job_page_icon_color text,
  ADD COLUMN IF NOT EXISTS job_page_apply_btn_bg text,
  ADD COLUMN IF NOT EXISTS job_page_apply_btn_text_color text,
  ADD COLUMN IF NOT EXISTS job_page_hero_bg text;